**

!frontend/
!frontend/package.json
!frontend/package-lock.json
!frontend/index.html
!frontend/vite.config.js
!frontend/eslint.config.js
!frontend/public/
!frontend/public/**
!frontend/src/
!frontend/src/**

!infra/
!infra/frontend/
!infra/frontend/nginx.conf
